name: Manyfold
version: "1.0.0"
slug: manyfold
description: Self-hosted digital asset manager for 3D print files
url: https://github.com/manyfold3d/manyfold
webui: http://[HOST]:[PORT:3214]
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
startup: application
boot: auto
ports:
  3214/tcp: 3214
ports_description:
  3214/tcp: Web interface
map:
  - share:rw
  - media:rw
hassio_api: true
hassio_role: default
options:
  puid: 1000
  pgid: 1000
schema:
  puid: int?
  pgid: int?
  multiuser_enabled: bool?
  registration_enabled: bool?
  usage_tracking_enabled: bool?
image: ghcr.io/manyfold3d/manyfold-solo:latest
