name: Manyfold
version: "1.3.0"
slug: manyfold
description: Self-hosted digital asset manager for 3D print files
url: https://github.com/manyfold3d/manyfold
webui: http://[HOST]:[PORT:3214]
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
startup: application
boot: auto
ports:
  3214/tcp: 3214
map:
  - share:rw
  - media:rw
  - config:rw
options:
  library_path: /media/HA-USB/3dprint-library
schema:
  library_path: str?
