name: Manyfold
version: "1.0.0"
slug: manyfold
description: Self-hosted digital asset manager for 3D print files
url: https://github.com/manyfold3d/manyfold
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
startup: application
boot: auto
ports:
  3214/tcp: 3214
ports_description:
  3214/tcp: Web interface
map:
  - config:rw
  - share:rw
  - media:rw
  - addons:ro
docker_api: true
privileged:
  - SYS_ADMIN
options:
  database_type: "sqlite"
  puid: 1000
  pgid: 1000
  model_libraries: []
schema:
  database_type: list(sqlite|postgresql|mysql)?
  database_host: str?
  database_port: port?
  database_name: str?
  database_user: str?
  database_password: password?
  puid: int?
  pgid: int?
  model_libraries:
    - str?
  multiuser_enabled: bool?
  registration_enabled: bool?
  usage_tracking_enabled: bool?
environment:
  SECRET_KEY_BASE: "file:///data/secret_key_base"
  DATABASE_ADAPTER: "sqlite3"
  DATABASE_NAME: "/data/manyfold.db"
  PUID: "1000"
  PGID: "1000"
